services:
  keycloak-local:
    image: quay.io/keycloak/keycloak:22.0.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_FRONTEND_URL: http://keycloak-local:8080
    command:
      - "start-dev"
      - "--import-realm"
    volumes:
      - ./keycloak/todo-realm-local.json:/opt/keycloak/data/import/todo-realm.json
    ports:
      - "8080:8080"
    networks:
      - local-network

  keycloak-dev:
    image: quay.io/keycloak/keycloak:22.0.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_FRONTEND_URL: http://keycloak-dev:8081
    command:
      - "start-dev"
      - "--import-realm"
    volumes:
      - ./keycloak/todo-realm-dev.json:/opt/keycloak/data/import/todo-realm.json
    ports:
      - "8081:8080"
    networks:
      - dev-network

  keycloak-prod:
    image: quay.io/keycloak/keycloak:22.0.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_FRONTEND_URL: http://keycloak-dev:8082
    command:
      - "start-dev"
      - "--import-realm"
    volumes:
      - ./keycloak/todo-realm-prod.json:/opt/keycloak/data/import/todo-realm.json
    ports:
      - "8082:8080"
    networks:
      - prod-network

  springboot-app-local:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=local
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080/actuator/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      - keycloak-local
    networks:
      - local-network

  springboot-app-dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8091:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080/actuator/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      - keycloak-dev
    networks:
      - dev-network


  springboot-app-prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8092:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080/actuator/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      - keycloak-prod
    networks:
      - prod-network

  nginx:
    image: "nginx:stable-alpine"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "80:80"
    depends_on:
      springboot-app-local:
        condition: service_healthy
      springboot-app-dev:
        condition: service_healthy
    networks:
      - local-network
      - dev-network
      - prod-network

networks:
  local-network:
  dev-network:
  prod-network: